
const lorem1 = `For, from the time that the Bishop of Rome had gotten to be acknowledged for bishop universal, by pretence of succession to St. Peter, their whole hierarchy, or kingdom of darkness, may be compared not unfitly to the kingdom of fairies; that is, to the old wives' fables in England concerning ghosts and spirits, and the feats they play in the night. And if a man consider the original of this great ecclesiastical dominion, he will easily perceive that the papacy is no other than the ghost of the deceased Roman Empire, sitting crowned upon the grave thereof: for so did the papacy start up on a sudden out of the ruins of that heathen power.`;

const lorem2 = `The attaining to this Soveraigne Power, is by two wayes. One, by Naturall force; as when a man maketh his children, to submit themselves, and their children to his government, as being able to destroy them if they refuse, or by Warre subdueth his enemies to his will, giving them their lives on that condition. The other, is when men agree amongst themselves, to submit to some Man, or Assembly of men, voluntarily, on confidence to be protected by him against all others. This later, may be called a Politicall Common-wealth, or Common-wealth by Institution; and the former, a Common-wealth by Acquisition. And first, I shall speak of a Common-wealth by Institution.`;

const lorem3 = `The opinion that any Monarch receiveth his Power by Covenant, that is to say on Condition, proceedeth from want of understanding this easie truth, that Covenants being but words, and breath, have no force to oblige, contain, constrain, or protect any man, but what it has from the publique Sword; that is, from the untyed hands of that Man, or Assembly of men that hath the Soveraignty, and whose actions are avouched by them all, and performed by the strength of them all, in him united. But when an Assembly of men is made Soveraigne; then no man imagineth any such Covenant to have past in the Institution; for no man is so dull as to say, for example, the People of Rome, made a Covenant with the Romans, to hold the Soveraignty on such or such conditions; which not performed, the Romans might lawfully depose the Roman People.`;

const lorem4 = `Eloquence, with flattery, disposeth men to confide in them that have it; because the former is seeming wisdom, the latter seeming kindness. Add to them military reputation and it disposeth men to adhere and subject themselves to those men that have them. The two former, having given them caution against danger from him, the latter gives them caution against danger from others. Want of science, that is, ignorance of causes, disposeth or rather constraineth a man to rely on the advice and authority of others. For all men whom the truth concerns, if they rely not on their own, must rely on the opinion of some other whom they think wiser than themselves, and see not why he should deceive them.`

const lorem5 = `But whatsoever is the object of any mans Appetite or Desire; that is it, which he for his part calleth Good: And the object of his Hate, and Aversion, evill, And of his contempt, Vile, and Inconsiderable. For these words of Good, evill, and Contemptible, are ever used with relation to the person that useth them: There being nothing simply and absolutely so; nor any common Rule of Good and evill, to be taken from the nature of the objects themselves; but from the Person of the man (where there is no Common-wealth;) or, (in a Common-wealth,) From the Person that representeth it; or from an Arbitrator or Judge, whom men disagreeing shall by consent set up, and make his sentence the Rule thereof.`;

export default { lorem1, lorem2, lorem3, lorem4, lorem5 };